#! /bin/sh

# Glosario:
# node: es una ventana
# desktop: es cada uno de los espacios que contienen nodes.

# Recarga las hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &
pkill -USR1 -x sxhkd

# Nombre de los desktops
bspc monitor eDP1 -d a s d f q w e 1 2 3 4 5

# Ancho del borde
bspc config border_width         2
# Gap entre nodos
bspc config window_gap          12

# TODO
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Reglas de los nodes
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop=q state=tiled layout=tiled follow=off
bspc rule -a firefox desktop=s state=tiled layout=monocle follow=off
bspc rule -a "kitty:wisdom-tree" desktop=a state=tiled layout=tiled
bspc rule -a "kitty:btop" desktop=e state=tiled layout=tiled follow=off
bspc rule -a spotify desktop=f state=tiled layout=tiled follow=off

# Poner un wallpaper random
# feh --randomize --bg-fill $HOME/wallpapers &
wal --backend wal -i $HOME/wallpapers &

# Colores desde pywal
# source the colors.
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# Abrir polybar
$HOME/.config/polybar/launch.sh

# Aplicaciones JAVA
wmname LG3D
